#!/usr/bin/env bash

installGo() {
	wget https://dl.google.com/go/go1.17.2.linux-amd64.tar.gz
	tar -xzf go1.17.2.linux-amd64.tar.gz
}

# Install golang binaries if it doesn't exist
# installGo

# Create all storage files
declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/githook"
mkdir "$PLUGIN_PATH/data"
echo > "$PLUGIN_PATH/data/hooks"
echo > "$PLUGIN_PATH/data/repos"
echo > "$PLUGIN_PATH/data/links"