#!/usr/bin/env bash

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/github-hook"

installGo() {
	wget https://dl.google.com/go/go1.17.2.linux-amd64.tar.gz
	tar -xzf go1.17.2.linux-amd64.tar.gz
	rm go1.17.2.linux-amd64.tar.gz
	# mv "./go" "$PLUGIN_PATH/"
}

# Install golang binaries
# installGo

# Install other dependencies
apt update
apt install screen -y
apt install ufw -y

# Create all storage files
mkdir "$PLUGIN_PATH/data"
echo -n > "$PLUGIN_PATH/data/hooks"
echo -n > "$PLUGIN_PATH/data/deploys"
echo -n > "$PLUGIN_PATH/data/links"
