#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN="$1"

if [[ "$PLUGIN" = "github-hook" ]]
then
	systemctl stop github-hook.service || true
	rm /etc/systemd/system/github-hook.service || true
	echo "Removed github-hook.service"
fi