#!/usr/bin/env bash

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/github-hook"

storeDeploy() {
	declare app=$1
	declare repoLink=$2
	echo "$app $repoLink" >> "$PLUGIN_PATH/data/deploys"
}

deployExist() {
	declare app=$1

	# Checks to see if app is already in local data file
	while read deployLine; do

		# Turn each line into array because the format 
		# is in "$app $repoLink"
		declare deployArr=($deployLine)
		[[ $app == ${deployArr[0]} ]] && return 0
	done < "$PLUGIN_PATH/data/deploys"
	return 1
}

deleteDeploy() {
	declare app=$1
	sed -i "/$app /d" "$PLUGIN_PATH/data/deploys"
}