#!/usr/bin/env bash

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/githook"

addHook() {
	declare webhook=$1
	declare webhookId=$2
	echo "$webhook $webhookId" >> "$PLUGIN_PATH/data/hooks"
	echo "current file"
	echo "$PLUGIN_PATH/data/hooks"
}

canAddHook() {
	declare webhook=$1
	while read hook; do
		declare hookArr=($hook)
		echo ${hookArr[0]}
		echo ${hookArr[1]}
		[[ $webhook == ${hookArr[0]} ]] && return 1
	done < "$PLUGIN_PATH/data/hooks"
	return 0
}

removeHook() {
	echo "removed"
}