#!/usr/bin/env bash

declare HOOK_DATA_PATH="$PLUGIN_AVAILABLE_PATH/githook/data/hooks"

addHook() {
	ls -l HOOK_DATA_PATH
	declare hook=$1
	echo "$hook" > HOOK_DATA_PATH
	canAddHook
}

canAddHook() {
	while read hook; do
		echo "$p"
	done < HOOK_DATA_PATH
}

removeHook() {
	echo "removed"
}