#!/usr/bin/env bash

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/github-hook"

storeLink() {
	declare hook=$1
	declare app=$2
	echo "$hook $app" >> "$PLUGIN_PATH/data/links"
}

linkExist() {
	declare hook=$1
	declare app=$2

	# Checks to see if link is already in local data file
	while read linkLine; do

		# Turn each line into array because the format 
		# is in "$hook $app"
		declare linkArr=($linkLine)
		[[ $hook == ${linkArr[0]} ]] && \
		[[ $app == ${linkArr[1]} ]] && return 0
	done < "$PLUGIN_PATH/data/links"
	return 1
}

deleteSpecificLink() {
	declare hook=$1
	declare app=$2
	sed -i "/$hook $app/d" "$PLUGIN_PATH/data/links"
}

deleteLinkByApp() {
	declare app=$1
	sed -i "/ $app/d" "$PLUGIN_PATH/data/links"
}

deleteLinkByHook() {
	declare hook=$1
	sed -i "/$hook /d" "$PLUGIN_PATH/data/links"
}