#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

createHook() {
	declare desc="Creates a new webhook and adds it to http server and github"
	declare cmd="create-hook"

	# Moves the input down by one so $1 will be the parameters after $cmd
	[[ "$1" == "$cmd" ]] && shift 1

	# The command format is $cmd $webhook $repository
	declare webhook=$1
	declare repository=$2

	echo "$webhook"
	echo "$repository"
}

echo "$@"
echo "$1"
echo "$2"
echo "$3"
echo "$4"
echo "$0"
createHook "$@"