#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

createHook() {
	declare desc="Creates a new webhook and adds it to http server and github"
	declare cmd="create-hook"

	[[ "$1" == "$cmd" ]] && shift 1
	# Support --app/$WEBHOOK_NAME flag
	# Use the following lines to reorder args into "$cmd $WEBHOOK_NAME $@""
	[[ -n $WEBHOOK_NAME ]] && set -- $WEBHOOK_NAME $@
	set -- $cmd $@

	echo "in function"
	echo "$1"
	echo "$2"
	declare WEBHOOK=$2

	echo "$WEBHOOK"
}

echo "$@"
echo "$1"
echo "$2"
echo "$3"
echo "$4"
echo "$0"
createHook "$@"