#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/githook"
declare webhookId=""

createDeploy() {
	declare desc="Creates a deployment link between a dokku app and repository"
	declare cmd="githook:deploy-create"

	# Moves the input down by one so $1 will be the parameters after $cmd
	[[ $1 == $cmd ]] && shift 1

	# The command format is $cmd $app $repository
	declare app=$1
	declare repository=$2

	# Make deploy data operations available
	source "$PLUGIN_PATH/data-operations/deploys"

	# Check if the app exist in local data
	if !(deployExist $app)
	then
		storeDeploy $app $repository
	else
		echo "err: given app already exist"
	fi
}

createDeploy "$@"