#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/githook"
declare webhookId=""

removeDeploy() {
	declare desc="Removes a deployment link for a dokku app"
	declare cmd="githook:deploy-remoe"

	# Moves the input down by one so $1 will be the parameters after $cmd
	[[ $1 == $cmd ]] && shift 1

	# The command format is $cmd $app
	declare app=$1

	# Make deploy data operations available
	source "$PLUGIN_PATH/data-operations/deploys"

	# Check if the app exist in local data
	if deployExist $app
	then
		removeDeploy $app
	else
		echo "err: given app does not exist"
	fi
}

removeDeploy "$@"