#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/github-hook"
source "$PLUGIN_PATH/utils"

deployAll() {
	declare desc="Deploys all dokku app that has a repository defined"
	declare cmd="github-hook:deploy-all"

	while read deployLine; do
		declare deployArr=($deployLine)
		declare app=${deployArr[0]}
		declare repoLink=${deployArr[1]}
		echo "=> Deploying app \"$app\" with repository $repoLink"
		dokku git:sync --build $app $repoLink 
	done < "$PLUGIN_PATH/data/deploys"
	echo "=> Finished deploying all apps!"
}

checkGithubAuth
deployAll