#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/githook"

removeDeploy() {
	declare desc="Removes deployment repository for a dokku app"
	declare cmd="githook:deploy-remove"

	# Moves the input down by one so $1 will be the parameters after $cmd
	[[ $1 == $cmd ]] && shift 1

	# The command format is $cmd $app
	declare app=$1

	# Make hook and link data operations available
	source "$PLUGIN_PATH/data-operations/hooks"
	source "$PLUGIN_PATH/data-operations/links"

	# Check if the app exist in local data
	if deployExist $app
	then
		deleteDeploy $app
		deleteLinkByApp $app
		echo "Successfully removed deploy for app \"$app\""
	else
		echo "err: given app does not exist"
	fi
}

removeDeploy "$@"