#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/github-hook"
source "$PLUGIN_PATH/utils"

deployAll() {
	checkLocalControlPort

	echo "=> Sending deploy all command to server"
	curl "localhost:$LOCAL_CONTROL_PORT/deploy-all" 	
}

deployAll