#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/github-hook"
source "$PLUGIN_PATH/utils"

removeDeploy() {
	declare desc="Removes deployment repository for a dokku app"
	declare cmd="github-hook:deploy-remove"

	# Moves the input down by one so $1 will be the parameters after $cmd
	[[ $1 == $cmd ]] && shift 1

	# The command format is $cmd $app
	declare app=$1

	# Make deploy and link data operations available
	source "$PLUGIN_PATH/data-operations/deploys"
	source "$PLUGIN_PATH/data-operations/links"

	# Check if the deployment exist for app in local data
	if deployExist $app
	then

		# Remove the deployment from local data and 
		# any links using the given app
		deleteDeploy $app
		deleteLinkByApp $app
		echo "=> Successfully removed deployment for app \"$app\"!"
		reload
	else
		echo "err: given app \"$app\" has no deployment"
	fi
}

removeDeploy "$@"