#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/github-hook"

createLink() {
	declare desc="Creates a link between a dokku app and hook"
	declare cmd="github-hook:link-create"

	# Moves the input down by one so $1 will be the parameters after $cmd
	[[ $1 == $cmd ]] && shift 1

	# The command format is $cmd $hook $app
	declare hook=$1
	declare app=$2

	# Make hook, deploy and link data operations available
	source "$PLUGIN_PATH/data-operations/hooks"
	source "$PLUGIN_PATH/data-operations/deploys"
	source "$PLUGIN_PATH/data-operations/links"

	# Check if the specific link combination exist in local data
	if !linkExist $hook $app
	then

		# Check if the given hook exist in local data
		if hookExist $hook
		then

			# Check if the deployment exist for app in local data
			if deployExist $app
			then			
				storeLink $hook $app
				echo "Successfully linked hook \"$hook\" with app \"$app\""
			else
				echo "err: Given app does not have deployment"
			fi
		else
			echo "err: Given hook does not exist"
		fi
	else
		echo "err: Given app and hook combination already exist"
	fi
}

createLink "$@"
source "$PLUGIN_PATH/subcommands/reload"