#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/githook"

removeDeploy() {
	declare desc="Removes the link between a dokku app and webhook"
	declare cmd="githook:link-remove"

	# Moves the input down by one so $1 will be the parameters after $cmd
	[[ $1 == $cmd ]] && shift 1

	# The command format is $cmd $app $webhook
	declare app=$1
	declare webhook=$2

	# Make link data operations available
	source "$PLUGIN_PATH/data-operations/links"

	# Check if the app exist in local data
	if linkExist $app $webhook
	then
		deleteSpecificLink $app $webhook
		echo "Successfully removed link between app \"$app\" and hook \"$webhook\""
	else
		echo "err: given app and hook combination does not exist"
	fi
}

removeDeploy "$@"