#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/github-hook"
source "$PLUGIN_PATH/utils"

createLink() {
	declare desc="Creates a link between a dokku app and hook"
	declare cmd="github-hook:link-create"

	# Moves the input down by one so $1 will be the parameters after $cmd
	[[ $1 == $cmd ]] && shift 1

	# The command format is $cmd $hook $app
	declare hook=$1
	declare app=$2

	# Make hook, deploy and link data operations available
	source "$PLUGIN_PATH/data-operations/hooks"
	source "$PLUGIN_PATH/data-operations/deploys"
	source "$PLUGIN_PATH/data-operations/links"

	# Check if the specific link combination exist in local data
	if ! linkExist $hook $app
	then

		# Check if the given hook exist in local data
		if hookExist $hook
		then

			# Check if the deployment exist for app in local data
			if deployExist $app
			then			
				storeLink $hook $app
				echo "=> Successfully linked hook \"$hook\" with app \"$app\"!"
				reload
			else
				echo "err: given app \"$app\" does not have deployment"
				exit 1
			fi
		else
			echo "err: given hook \"$hook\" does not exist"
			exit 1
		fi
	else
		echo "err: given app \"$app\" and hook \"$hook\" combination already exist"
		exit 1
	fi
}

createLink "$@"
