#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/githook"

createLink() {
	declare desc="Creates a link between a dokku app and webhook"
	declare cmd="githook:link-create"

	# Moves the input down by one so $1 will be the parameters after $cmd
	[[ $1 == $cmd ]] && shift 1

	# The command format is $cmd $app $webhook
	declare app=$1
	declare webhook=$2

	# Make hook, deploy and link data operations available
	source "$PLUGIN_PATH/data-operations/hooks"
	source "$PLUGIN_PATH/data-operations/deploys"
	source "$PLUGIN_PATH/data-operations/links"

	# Check if the specific link combination exist in local data
	if !(linkExist $app $webhook)
	then

		# Check if the deployment exist for app in local data
		if deployExist $app
		then

			# Check if the given webhook exist in local data
			if hookExist $webhook
			then
				storeLink $app $webhook
				echo "Successfully linked app \"$app\" with hook \"$webhook\""
			else
				echo "err: given hook does not exist"
			fi
		else
			echo "err: given app does not have deployment"
		fi
	else
		echo "err: given app and hook combination already exist"
	fi
}

createLink "$@"