#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/github-hook"
source "$PLUGIN_PATH/utils"

removeDeploy() {
	declare desc="Removes the link between a dokku app and hook"
	declare cmd="github-hook:link-remove"

	# Moves the input down by one so $1 will be the parameters after $cmd
	[[ $1 == $cmd ]] && shift 1

	# The command format is $cmd $hook $app
	declare hook=$1
	declare app=$2

	# Make link data operations available
	source "$PLUGIN_PATH/data-operations/links"

	# Check if the specific link combination exist in local data
	if linkExist $hook $app
	then
		deleteSpecificLink $hook $app
		echo "=> Successfully removed link between hook \"$hook\" and app \"$app\"!"
		reload
	else
		echo "err: given app \"$app\" and hook \"$hook\" combination does not exist"
		exit 1
	fi
}

removeDeploy "$@"
