#!/usr/bin/env bash
# set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/github-hook"
declare SCREEN_NAME="github-hook"

start() {

	# When there's a screen running, end it
	if screen -list | grep -q $SCREEN_NAME
	then
		echo "Github hook server already running, ending the previous session"
		screen -S $SCREEN_NAME -X quit
	fi

	# Make a new screen
	echo "Starting up github hook server now..."
	screen -dmS $SCREEN_NAME

	# Run golang server in the screen
	# screen -S $SCREEN_NAME -X stuff 'cd '$PLUGIN_PATH'\n'
	# screen -S $SCREEN_NAME -X stuff '~/go/bin/go run ./main.go\n'
	screen -S $SCREEN_NAME -X stuff '~/go/bin/go run /home/dokku/gotest/main.go \n'

	echo "Server is up!"
}

start "$@"