#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

declare PLUGIN_PATH="$PLUGIN_AVAILABLE_PATH/github-hook"
declare SCREEN_NAME="github-hook"

start() {

	# Login to dokku github
	dokku git:auth github.com $GITHUB_USERNAME $GITHUB_TOKEN

	if screen -list | grep -q $SCREEN_NAME
	then

		# When there's screen run a Ctrl+C to stop any existing programs
		echo "thre is stuff"
		screen -S $SCREEN_NAME -X stuff '^C'
	else

		# If there are no screens the make a new one
		echo "thre is no stuff"
		screen -dmS $SCREEN_NAME
	fi

	# Run golang server in the screen
	screen -S $SCREEN_NAME -X stuff 'cd '$PLUGIN_PATH'\n ~/go/bin/go run '$PLUGIN_PATH'/main.go\n'
}

start "$@"